config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="new">
  <div class="header">
    <h3>Wikinimous</h3>
  </div>
  <div class="form">
    <%= form_for(@article) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_field :content %>
      <%= f.submit %>
    <% end %>



  </div>
</div>

app/views/articles/index.html.erb
<div class="header">

  <h3>Wikinimous</h3>
  <%= link_to "Create a new article", "articles/new" %>
</div>
<div class="container">

  <% @articles.each do | article | %>
    <div class = "paired">
      <h2><%= link_to article.title, article_path(article) %></h3>
      <h5><%= article.content %></h5>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="new"></div>
  <div class="header">
    <h3>Wikinimous</h3>
    <%= link_to "Create a new article", "new" %>
  </div>
  <div class="form">
    <%= form_for(@article) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_field :content, as: :text, input_html: { rows: "2" } %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="header">
  <h3>Wikinimous</h3>
  <%= link_to "Create a new article", "new" %>
</div>
<div class="container">
  <div class="content">
  <h1> <%= @article.title %> </h1>
  <p> <%= @article.content %> </p>
</div>
  <div class="icons">
  <%= link_to ('<i class="far fa-edit"></i>').html_safe, "/articles/#{@article.id}/edit"  %>

  <%= link_to article_path(@article.id), method: :delete, data: { confirm: "Delete #{@article.title}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
   </li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/7ba933a92a.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>